### ISSUE TITLE
Mocking framework classes with unavailable initializers

### ISSUE THREAD

**Issue by perryao** [DeliciousRaspberryPi/MockFive#1]
@DeliciousRaspberryPi Sorry to open this up as an issue, but wasn't sure where else to contact you. Do you know of a solution for mocking framework classes that hide their initializers (either with MockFive or in general)? I'm trying to test a central manager class that wraps CoreBluetooth, and I'd like to be able to verify that the state is what I'm expecting after the CBCentralManagerDelegate methods are called. Problem is, CBPeripheral has an unavailable initializer, so I can't find a way to mock it.

**Comment by DeliciousRaspberryPi** [comment]
Ok, so correct me if I'm wrong--my understanding is that you need to make a mock of CBPeripheral that you can pass to a CBCentralManagerDelegate method, so that you can watch how that CBPeripheral has been operated.

MockFive keeps all of its state in global variables outside instances of Mock(), except for the object identifier.  Since it only uses a default value:  'let mockFiveLock = lock()', adopting Mock should not require you to override an initializer.

You should be able to create a mock like this:

    class CBPeripheralMock: CBPeripheral, Mock {
        let mockFiveLock = lock()

**Comment by DeliciousRaspberryPi** [comment]
Ok, so correct me if I'm wrong--my understanding is that you need to make a mock of CBPeripheral that you can pass to a CBCentralManagerDelegate method, so that you can watch how that CBPeripheral has been operated.  There's a protocol-oriented solution for this.  You will have to do something that looks just a little bit funky--but, you can get what you want with type safety, and MockFive can help!

With a hidden initializer, Apple's saying, "You shouldn't create instances of this class".  So, let's not.  Instead, let's create a type that's more general than a CBPeripheral, that represents what we want: some object that supports the method's we're interested in:

    protocol BluetoothPeripheral {
        func discoverServices(serviceUUIDs: [CBUUID]?)
        func discoverCharacteristics(characteristicUUIDs: [CBUUID]?, forService service: CBService)
    }

Now, because CBPeripheral already has these methods, we can declare its conformance as a formality, like so:

    extension CBPeripheral: BluetoothPeripheral {}

There's one more hoop to jump through.  Obviously, you still have to implement the CBCentralManagerDelegate protocol, which requires the 'native' type of CBPeripheral.  In order to test this, you'll need to have that function act as dispatch:

    //  This goes in your production central manager delegate
    //MARK: CBCentralManagerDelegate
    func centralManager(central: CBCentralManager, didConnectPeripheral peripheral: CBPeripheral) {
        real_centralManager(central: central, peripheral: peripheral)

**Comment by DeliciousRaspberryPi** [comment]
Ok, so correct me if I'm wrong--my understanding is that you need to make a mock of CBPeripheral that you can pass to a CBCentralManagerDelegate method, so that you can watch how that CBPeripheral has been operated.  There's a protocol-oriented solution for this.  You will have to do something that looks just a little bit funky--but, you can get what you want with type safety, and MockFive can help!

With a hidden initializer, Apple's saying, "You shouldn't create instances of this class".  So, let's not.  Instead, let's create a type that's more general than a CBPeripheral, so that it could represent a CBPeripheral OR a mock of it.

    protocol BluetoothPeripheral {
        // Declare the methods you're interested in from CBPeripheral
        func discoverServices(serviceUUIDs: [CBUUID]?)
        func discoverCharacteristics(characteristicUUIDs: [CBUUID]?, forService service: CBService)
    }

Now, because CBPeripheral already has these methods, we can declare its conformance as a formality, like so:

    extension CBPeripheral: BluetoothPeripheral {} // No implementation necessary

There's one more hoop to jump through.  Obviously, you still have to implement the CBCentralManagerDelegate protocol, which requires the 'native' type of CBPeripheral.  You need your behavior to depend on your more general type, though, 'BluetoothPeripheral'.  So, you need to make untested "dispatch" methods that get calls from the bluetooth manager, and then just bounce them to your actual method.

    //  This goes in your production central manager delegate
    //MARK: CBCentralManagerDelegate
    func centralManager(central: CBCentralManager, didConnectPeripheral peripheral: CBPeripheral) {
        real_centralManager(central: central, peripheral: peripheral)
    }

    func real_centralManager(central: CBCentralManager, didConnectPeripheral peripheral: BluetoothPeripheral) {
        // Real logic goes here
    }

So!  Now, if you were to have a mock, and if that mock were to conform to 'BluetoothPeripheral', you could then inject it: where you would expect your bluetooth manager to call 'centralManager(_:didConnectPeripheral:)', you would call 'real_centralManager(_:didConnectPeripheral:)' and pass a mock.  For the sake of completeness, such a mock might look like...

    struct BluetoothPeripheralMock: BluetoothPeripheral, Mock {
        let mockFiveLock = lock()
    
        func discoverServices(serviceUUIDs: [CBUUID]?) {
            stub(identifier: "discover services", arguments: serviceUUIDs)
        }
    
        func discoverCharacteristics(characteristicUUIDs: [CBUUID]?, forService service: CBService) {
            stub(identifier: "discover characteristics", arguments: characteristicUUIDs, service.UUID)
        }
    }

And after being injected, you can just examine your 'mockPeripheral.invocations' to determine what state configuration has been done.

Happy testing!
