### ISSUE TITLE
Typed identifiers

### ISSUE THREAD

**Issue by jakecraige** [DeliciousRaspberryPi/MockFive#2]
First, this project looks really interesting. I love how it allows you to get the benefits of mocking and dynamically changing things, in Swift.

One thing that caught my eye was that the identifiers are typed as strings which opens up the possibility of having a typo cause something to behave unexpectedly. To combat this, having it typed by something like an `enum` seems like one way to get around this.

What do you think?

**Comment by DeliciousRaspberryPi** [comment]
Well, what I think is that I've been struggling to come up with a proper solution to this problem, because I agree with you completely.  I'm trying to stir up a general discussion on the issue [here](https://github.com/DeliciousRaspberryPi/MockFive/issues/3), but to digress a little here...

The information we're trying to wrestle down with code here is, "Does the identifier you're registering correspond with a valid function in the object you're attempting to mock?".  Adding an enumeration proves unsatisfactory, because the problem doesn't exactly go away: you might create cases in the enum that you don't use in mocks, or you might typo an identifier in a mock and not notice until you discover incorrect behavior.

The core of the issue is that the identity of a function in Swift is meant to exist at compile time, and not to exist at runtime.  Functions have no unique identifiers, they do not conform to `Hashable`, they do not conform to `Equatable`.  Swift specifically has as a language goal that access to pointers is only for interfacing with other, less safe languages.

As such, we can't actually make any sort of computation that checks whether these mocks are "well formed", in that they have an identifier for each function they should be mocking, and that the identifier is unique.  The current approach leaves completely open the possibility of using an enum, but doesn't lock you into it:

    protocol MySimpleProtocol {
        func function()
    }
    
    struct MySimpleProtocolMock: MySimpleProtocol, Mock {
        let mockFiveLock = lock()
        
        enum MySimpleProtocolFunctions: String {
            case Function = "function"
        }
        
        func function() {
            stub(identifier: MySimpleProtocolFunctions.Function.rawValue)
        }
    }
